apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp-container
        image: 055686730858.dkr.ecr.us-east-1.amazonaws.com/my_ecr_repo:web_app
        env:
        - name: DBHOST
          value: "10.96.186.248"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 8080
